#!/usr/bin/env bash

LOX_VISIBLE=${LOX_VISIBLE:-''}

__datafile=${__datafile:-$HOME/.lox}

__puton__() {
  if [ -d $__datafile ]; then
    echo 'datafile cannot be a directory: '$__datafile
    return
  fi
  touch $__datafile
}

for__help='@arg logfile @does use the given file as lox file.'
for__ () {
  __datafile=$1
  shift
  __run "$@"
}

here__help='Uses a local repository: PWD/.lox'
here__() {
  __datafile=$(pwd)/.lox
  __run "$@"
}

start__help='Starts logging.'
start__ () {
  echo "Start logging. Press Ctrl+C to stop...";
  local cmd prev_cmd
  cmd__ pwd
  until false; do
    __process_line
  done
}

show__help='Displays the log. @see tail'
show__ () {
  less $__datafile
}

tail__help='Usage: tail [N] ; display the last N line from the log. @see show'
tail__ () {
  if [ ! -z $1 ]; then
    tail $__datafile -n$1
  else
    tail $__datafile
  fi
}

cmd__help='Executes a lox command; for internal and external use.'
cmd__ () {
  local cmd=$@
  local -A list
  __list list
  case "$cmd" in
    ${list[echo]})
	echo $prev_cmd;
	echo "> echo";
	;;
    ${list[list]})
	less +G $__datafile;
	;;
    ${list[clear]})
	clear;
	;;
    ${list[date]})
        date
	;;
    ${list[pwd]})
	__write_log $(pwd)
	;;
    ${list[exit]})
        echo "Done."
	exit
	;;
    "")
	echo "[Null]";
	;;
    ${list[default]})
        prev_cmd="$cmd"
        __write_log "${cmd}"
        len=${#cmd}
	echo "[Logged "${#cmd}" character(s).]"
	;;
  esac
}

__list () {
  local -n arr=$1
  shopt -s extglob
  arr[echo]='@(echo)'
  arr[exit]='@(x|q)'
  arr[list]='@(list)'
  arr[clear]='@(clear)'
  arr[date]='@(date)'
  arr[pwd]='@(pwd)'
  arr[default]='@(*)'
}

__process_line () {
  if test -z $LOX_VISIBLE; then
    read -s cmd
  else
    read cmd
  fi
  cmd__ $cmd
}

__write_log () {
  local text=$1
  echo $(date '+%Y-%m-%d %H:%M:%S') $text >> $__datafile
  return
}

. undies

