#!/usr/bin/env bash


datafile__=${datafile__:-$HOME/.lox}

__puton__() {
  touch $datafile__
}

start__help='Starts logging.'
start__ () {
  echo "Start logging. Press Ctrl+C to stop...";
  cmd=""
  prev_cmd=""
  until false; do
    __process_line
  done
}

__process_line () {
  read -s cmd;
  case "$cmd" in
    "echo")
	echo $prev_cmd;
	echo "> echo";
	;;
    "list")
	less +G $datafile;
	;;
    "clear")
	clear;
	;;
    "date")
        date
	;;
    'pwd')
	__write_log $(pwd)
	;;
    "exit") 
        echo "Done."
	exit
	;;
    "")
	echo "[Null]";
	;;
    *)
        prev_cmd="$cmd"
        __write_log "${cmd}"
        len=${#cmd}
	echo "[Logged "${#cmd}" character(s).]"
	;;
  esac
}

__write_log () {
  local text=$1
  echo $(date '+%Y-%m-%d %H:%M:%S') $text >> $datafile__
  return
}

. undies

